sudo: required
addons:
  chrome: stable

dist: xenial

services:
  - xvfb

language: node_js

node_js:
  - "8.9.1"

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

cache:
  directories:
    - ~/.npm
    - "node_modules"

notifications:
  email: false

before_script:
  - sleep 3

script:
  - meteor create --bare test
  - cd test
  - meteor npm i --save selenium-webdriver@3.6.0 chromedriver@2.36.0 simpl-schema chai
  - METEOR_PACKAGE_DIRS="../" TEST_BROWSER_DRIVER=chrome meteor test-packages --exclude-archs web.browser.legacy --once --driver-package meteortesting:mocha ../
